name: JS Actions

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Ha-Ha
        uses: ./.github/actions/joke-action
        with:
          owner: '${{ github.repository_owner }}'
          repository: '${{ github.event.repository.name }}'
          issue_number: '${{ github.event.issue.number }}'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
